### ISSUE TITLE
Discrepancy between builtin sum() and jlist.sum() when summing integers

### ISSUE THREAD

**Issue by cycloid** [llllllllll/jlist#5]
I noticed a discrepancy between builtin sum() and jlist.sum() when summing long lists of large (up to 60 bit) integers.  It looks like the transition to overflow from 64 bit to bignum results causes a problem.  Comparison to behavior of numpy included for completeness.

```python
"""Test for differences summing list(), jlist(), and ndarray()'s of ints
related to integer overflow"""

from random import randrange

import jlist as jl
import numpy as np


# make a long list of potentially large ints that are < 64 bits
builtin_ints = list(randrange(2 ** 45) for _ in range(1_000_000))
jlist_ints = jl.jlist(builtin_ints)
numpy_ints = np.array(builtin_ints)

def explicit_sum(x):

    result = 0
    for i in x:
        result += int(i)
    return result

print(
    "",
    "explicit python loop over list(), and built-in sum() results for list(), jlist(), and ndarray() ints",
    explicit_sum(builtin_ints),
    sum(builtin_ints),
    sum(jlist_ints),
    sum(numpy_ints),
    "",
    "explicit python loop over jlist(), and jlist.sum() results for list(), jlist(), and ndarray() ints",
    explicit_sum(jlist_ints),
    jl.sum(builtin_ints),
    jl.sum(jlist_ints),
    jl.sum(numpy_ints),
    "",
    "explicit python loop over ndarray(), and numpy.sum() results for list(), jlist(), and ndarray() ints",
    explicit_sum(numpy_ints),
    np.sum(builtin_ints),
    np.sum(jlist_ints),
    np.sum(numpy_ints),
    sep="\n",
)

```

Results:

```
jlist_test_simple.py:30: RuntimeWarning: overflow encountered in long_scalars
  sum(numpy_ints),
jlist_test_simple.py:36: RuntimeWarning: overflow encountered in long_scalars
  jl.sum(numpy_ints),

explicit python loop over list(), and built-in sum() results for list(), jlist(), and ndarray() ints
17597094098869121677
17597094098869121677
17597094098869121677
-849649974840429939

explicit python loop over jlist(), and jlist.sum() results for list(), jlist(), and ndarray() ints
17597094098869121677
17597094098869121677
26820450324034052931
-849649974840429939

explicit python loop over ndarray(), and numpy.sum() results for list(), jlist(), and ndarray() ints
17597094098869121677
-849649974840429939
-849649974840429939
-849649974840429939

```

```
System Version:	macOS 10.14.6 (18G84)
Kernel Version:	Darwin 18.7.0

Darwin mojo 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

g++-9 (Homebrew GCC 9.1.0) 9.1.0
```

**Comment by llllllllll** [comment]
Thanks for this issue with the comprehensive repro and comparisons. I found the issue and opened a PR here: https://github.com/llllllllll/jlist/pull/6

I added a test that mostly adapts what you have here except for the numpy stuff, would you mind taking a look.

**Comment by cycloid** [comment]
I'm not qualified to review the code but I've tested the change and it passes my tests.

Thanks very much, great response!  And thanks for exploring the possibility of unboxed lists.

I'll leave this open for you to close when you've merged, unless you'd like it closed now.

Edit: it occurs to me you wanted me to look at the test, not the .cc.  LGTM.  I did a lot of paranoid checking in some early tests to ensure that elements were being stored correctly.  The only thing I can think that this test doesn't cover is if the last element is the one that puts the sum > 64 bits.

**Comment by llllllllll** [comment]
I will add special cases for the first and last element tripping over to unboxed, and then merge. The `.cc` change is just incrementing a counter in the loop (instead of leaving it at 0) so I am happy to merge if the tests look good.

Thanks again for the report, and for looking over the tests.

**Comment by cycloid** [comment]
The tests looks good to me.
